### ISSUE TITLE
Performance of `enumFromTo` vs. `enumFromN`

### ISSUE THREAD

**Issue by epsilonhalbe** [haskell/vector#116] opened 2016-05-15 13:42 UTC
I came upon the following curiosity:

While the documentation says

> `enumFromN :: (Unbox a, Num a) => a -> Int -> Vector a`
>
> *O(n)* Yield a vector of the given length containing the values x, x+1 etc.
> This operation is usually more efficient than `enumFromTo`.

in the following samples - `enumFromTo` seems to be better than `enumFromN`.

`sumV.hs`
-

```haskell
{-import           Data.Vector as V-}
import           Data.Vector.Unboxed as V

main :: IO ()
main = print $ V.sum $ V.enumFromN (1::Int) 100000000
```

`sumV2.hs`
-

```haskell
{-import           Data.Vector as V-}
import           Data.Vector.Unboxed as V

main :: IO ()
main = print $ V.sum $ V.enumFromTo (1::Int) 100000000
```

The output of the compiled programs (`-O2 -with-rtsopts="-sstderr"`) using `ghc-7.10.3` and `stack-1.1.0` and `resolver=lts-5.17`.

```
$ > stack exec -- time sumV
5000000050000000
     800,051,984 bytes allocated in the heap
           7,808 bytes copied during GC
          44,312 bytes maximum residency (1 sample(s))
          21,224 bytes maximum slop
             764 MB total memory in use (0 MB lost due to fragmentation)

                                     Tot time (elapsed)  Avg pause  Max pause
  Gen  0         1 colls,     0 par    0.000s   0.000s     0.0000s    0.0000s
  Gen  1         1 colls,     0 par    0.001s   0.004s     0.0041s    0.0041s

  INIT    time    0.000s  (  0.000s elapsed)
  MUT     time    0.488s  (  0.507s elapsed)
  GC      time    0.001s  (  0.004s elapsed)
  EXIT    time    0.001s  (  0.004s elapsed)
  Total   time    0.492s  (  0.515s elapsed)

  %GC     time       0.3%  (0.8% elapsed)

  Alloc rate    1,639,218,652 bytes per MUT second

  Productivity  99.7% of total user, 95.2% of total elapsed

0.30user 0.19system 0:00.51elapsed 95%CPU (0avgtext+0avgdata 784828maxresident)k
0inputs+0outputs (0major+825minor)pagefaults 0swaps
```

and for the second version

```
$ > stack exec -- time sumV2
5000000050000000
          51,872 bytes allocated in the heap
           3,408 bytes copied during GC
          44,312 bytes maximum residency (1 sample(s))
          17,128 bytes maximum slop
               1 MB total memory in use (0 MB lost due to fragmentation)

                                     Tot time (elapsed)  Avg pause  Max pause
  Gen  0         0 colls,     0 par    0.000s   0.000s     0.0000s    0.0000s
  Gen  1         1 colls,     0 par    0.000s   0.000s     0.0001s    0.0001s

  INIT    time    0.000s  (  0.000s elapsed)
  MUT     time    0.055s  (  0.057s elapsed)
  GC      time    0.000s  (  0.000s elapsed)
  EXIT    time    0.000s  (  0.000s elapsed)
  Total   time    0.056s  (  0.058s elapsed)

  %GC     time       0.2%  (0.2% elapsed)

  Alloc rate    946,385 bytes per MUT second

  Productivity  99.5% of total user, 97.1% of total elapsed

0.05user 0.00system 0:00.05elapsed 94%CPU (0avgtext+0avgdata 3564maxresident)k
0inputs+0outputs (0major+179minor)pagefaults 0swaps
```

Note: This behaviour is not reproducible with `Data.Vector` instead of `Data.Vector.Unboxed`

**Comment by dolio** [comment] 2016-05-16 02:38
The heap allocation of `sumV` is enormous compared to `sumV2`. The max residency is the same, so I'm guessing it's a failure of the optimizer to completely eliminate boxing. This also explains the inability to reproduce with boxed vectors, where no unboxing would happen (I expect).

**Comment by dolio** [comment] 2016-05-16 04:34
So, actually, I'm having trouble reproducing this. I get the bad results in both cases. And I'm pretty sure the bad results are caused by actually allocating a vector, because I see Vectors in the core. 800 million bytes is also exactly enough space to store 100 million unboxed ints, so that would correspond to such a vector being allocated (and the 1 heap sample missed it, I guess).

Can you add -ddump-simpl -ddump-to-file to your GHC options, and attah the files perhaps? The fast one would be interesting to see.

Also, what version of vector is this with? 0.11?

**Comment by epsilonhalbe** [comment] 2016-05-16 10:46
Hey, I have added a git repo to make it more easy to reproduce (at least I hope).

- https://github.com/epsilonhalbe/issue116

Yes I use vector-0.11.0.0 - from stackage - the compiler is ghc-7.10.3 - the one from the hvr-ppa-repository on a 64bit-linux (mint) machine.

**Comment by dolio** [comment] 2016-05-16 13:14
Is your sumV.txt accidentally from a run of sumV2? It has the good looking RTS output.

Anyhow, the clear difference in the core is that sumV builds an array/vector, and sumV2 doesn't. However, I can't make this happen on my machine. Both build a vector.

I don't use stack, but that shouldn't be making a difference unless it passes some different options to GHC or something. I was wondering if it might be a platform difference, but we're both running 64-bit linux.

Either of these things not fusing is a bug in any case, though. They should both have the good performance you get with V2.

**Comment by epsilonhalbe** [comment] 2016-05-16 13:38
hey - sorry there might have been a mix up
I ran the program again and now it should be correct.
I also tried to clone the `vector` repo master - but saw no different output

**Comment by cartazio** [comment] 2016-05-16 15:44
Has anyone run the same comparison with 8.0 yet?

**Comment by epsilonhalbe** [comment] 2016-05-16 17:27
I have tried - same problem happening

also adding the ghc-8.0.0 dump files to the git-repo (the ghc is from the hvr-ppa)

```
$ > ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.0.0.20160511
$ > cabal --version
cabal-install version 1.24.0.0
compiled using version 1.24.0.0 of the Cabal library
$ > cabal install --allow-newer
$ > time cabal run sumV
Preprocessing executable 'sumV' for issue116-0.1.0.0...
Running sumV...
5000000050000000
     800,051,848 bytes allocated in the heap
           7,952 bytes copied during GC
          44,384 bytes maximum residency (1 sample(s))
          21,152 bytes maximum slop
             764 MB total memory in use (0 MB lost due to fragmentation)

                                     Tot time (elapsed)  Avg pause  Max pause
  Gen  0         1 colls,     0 par    0.000s   0.000s     0.0000s    0.0000s
  Gen  1         1 colls,     0 par    0.047s   0.048s     0.0481s    0.0481s

  INIT    time    0.000s  (  0.000s elapsed)
  MUT     time    0.863s  (  0.863s elapsed)
  GC      time    0.047s  (  0.048s elapsed)
  EXIT    time    0.047s  (  0.048s elapsed)
  Total   time    0.958s  (  0.959s elapsed)

  %GC     time       4.9%  (5.0% elapsed)

  Alloc rate    926,646,350 bytes per MUT second

  Productivity  95.1% of total user, 95.0% of total elapsed

cabal run sumV  0,80s user 0,70s system 106% cpu 1,417 total
$ >  time cabal run sumV2
Preprocessing executable 'sumV2' for issue116-0.1.0.0...
Running sumV2...
5000000050000000
          51,736 bytes allocated in the heap
           3,480 bytes copied during GC
          44,384 bytes maximum residency (1 sample(s))
          17,056 bytes maximum slop
               1 MB total memory in use (0 MB lost due to fragmentation)

                                     Tot time (elapsed)  Avg pause  Max pause
  Gen  0         0 colls,     0 par    0.000s   0.000s     0.0000s    0.0000s
  Gen  1         1 colls,     0 par    0.000s   0.000s     0.0001s    0.0001s

  INIT    time    0.000s  (  0.000s elapsed)
  MUT     time    0.104s  (  0.104s elapsed)
  GC      time    0.000s  (  0.000s elapsed)
  EXIT    time    0.000s  (  0.000s elapsed)
  Total   time    0.105s  (  0.105s elapsed)

  %GC     time       0.1%  (0.1% elapsed)

  Alloc rate    496,947 bytes per MUT second

  Productivity  99.7% of total user, 100.4% of total elapsed

cabal run sumV2  0,47s user 0,06s system 108% cpu 0,489 total
```

**Comment by dolio** [comment] 2016-05-16 23:16
I've tried with 8, as well, and get the same results as I get on 7.10.3. Both examples are the bad behavior.

Quite odd.

**Comment by cartazio** [comment] 2016-07-24 19:40
since we dont seem to be able to reproduce this, closing

**Closed by cartazio** 2016-07-24 19:40 UTC
Labels: cant-reproduce, question
