### ISSUE TITLE
Why not re-export functions from Data.Vector.Generic?

### ISSUE THREAD

**Issue by winterland1989** [haskell/vector#162] opened 2017-04-09 07:47 UTC
I found that `Data.Vector`, `Data.Vector.Unboxed`, `Data.Vector.Primitive` and `Data.Vector.Storable` all export their own version of vector operations, but most of these operations are just bindings to `Data.Vector.Generics`, this design force user to use qualification. So the question is: Why not simply re-export these functions from `Data.Vector.Generic`?

**Comment by dolio** [comment] 2017-04-20 03:00
I honestly don't know why the library was designed this way. The only purpose it really serves is to nail down the type of vector being used. Maybe that's useful enough in some cases? Not sure.

**Comment by winterland1989** [comment] 2017-05-04 10:37
After doing some experiments, i found no differences in performance or type inference, i think it worth considering to remove these duplicated bindings in favor of re-export.

**Comment by Shimuuar** [comment] 2020-02-02 18:31
Having 4 specializations: (boxed,unboxed,storable,primitive) is significant maintenance burden. When you add/change something you have to do it in 5 places/ It's easy to forget to change something: #262 (missing `imapM`) as an example.

**Comment by lehins** [comment] 2020-02-02 19:08
> Why not simply re-export these functions from `Data.Vector.Generic`?

All functions that have synonyms in specialized modules are exported from `Data.Vector.Generic`. So if a user chooses to use them instead of specialized versions they are free to do so. But this specialization like design is very helpful for the end user that only cares about a singe vector type:

* Cleaner signatures
* Better type inference

Let's look at down sides:

* "Increases the maintenance" -  well what doesn't. Any feature requires work. Question is, is this feature worthwhile the overhead
* "Compile faster" - not even an argument. I don't think that compilation time overhead for function synonyms can even measured. Glad to be proven wrong though.
* Documentation - this is the biggest one in my opinion. But I think we can solve it in common fashion of linking to the generic function, which would have the full doc with examples. For example

```haskell
module Data.Vector.Primitive

-- | See `G.head`
head :: Vector a -> a
head = G.head
```

* "Easy to forget" is a good argument, but a better counterargument is that we need to have tests for each function, for each representation, since we do have to test each vector type regardless. Then forgetting is no longer a problem. Here is a good example of how to write such tests:

https://github.com/haskell/vector/blob/9cf8acccb54b0894eb3d03991cef9c50a4b0128d/tests/Tests/Vector/UnitTests.hs#L71-L74


Why this design was chosen, I am not sure. Next time I see Roman, I'll ask him. If I had to guess, back in a day specializing function to a particular type of vector actually improved performance, but I have nothing to back up this hypothesis.

The biggest counter-argument of all! This design has been around for over a decade, enormous amount of software has been written to rely on this design, changing it now is simply not acceptable!

Sorry guys, but I am closing this as won't fix.

**Comment by Shimuuar** [comment] 2020-02-02 20:00
Partial counterpoint. I agree with you on API breakage. But worst problem is documentation. We can test for lost functions. We can't test that haddocks match and doing same thing five times with slight variations and without errors is near limit of human ability. 

What we're doing here manually is monomorphisation of module. But process is entirely mechanical maybe we can do something about it. I could only think about code generation which has its own problems...

**Comment by lehins** [comment] 2020-02-02 21:43
@Shimuuar lol. Don't exaggerate :D 
> ...  is near limit of human ability.

I opened a ticket where we can discuss haddock duplication issue #296 

@cartazio Please don't tell me you are actually considering changing the overall design of the library!?!?

**Comment by cartazio** [comment] 2020-02-02 21:44
@lehins  this was also requested/proposed by @merijn  in https://github.com/haskell/vector/issues/262 (as @Shimuuar  notices).

honestly, i think if we had a way to express "reexport this module but expose it as a simpler type", which has come up in list vs traversable discussions, that would address the inference concern.

i'd love to see an example where in compiled code this inference would happen and be a usability issue (cf top level bindings etc having types), and for things like GHCI, maybe better/augmented defaulting would work? 

i think this duplication is currently a huge cost that honestly could be better addressed by improving ghc to support the UX.

I think we sholdn't break stuff, but i'm not sure the having the .Generics operations directly exported would break any code. its at least worth experimenting sans release with this direction to see where it goes

**Comment by cartazio** [comment] 2020-02-02 21:46
i'm actually saying 

1) lets precisely understand what impact it would have on type inference and how

2) lets make sure that any discrepencies there get associated ghc / cabal level tooling to remove that delta from end library users

3) if we can keep / improve the current user experience while not hurting anyone, thats a win.
But it will need to be evidence driven, yes or no.

**Comment by cartazio** [comment] 2020-02-02 21:47
it could very well be @lehins is correct and everyone else is a dreamer. but thats an experiment / not released code experiment that we can try out ourselves and discuss/evaluate.

I think any problems we hit in such an experiment will be easy to turn into tickets for ghc/cabal/(or perhaps that crazy backpack thing?)

**Comment by cartazio** [comment] 2020-02-02 21:50
(i hope i'm making sense, i'm not saying reexporting must needs be the way, but naively, it seems like seeing what problems get triggerd by such a experiment branch of vector would be interesting!)

**Comment by lehins** [comment] 2020-02-02 21:51
H
Here is a simple example. What is the inferred type signature of this function:
```haskell
showIfFirstEqual v1 v2 =
  if VG.head v1 == VG.last v2
    then show v1
    else show v2
```

vs this:

```haskell
showIfFirstEqual v1 v2 =
  if VP.head v1 == VP.last v2
    then show v1
    else show v2
```

Second one is obvious where the latter is not so much:

```haskell
showIfFirstEqual ::  (Eq a, VG.Vector v1 a, VG.Vector v2 a, Show (v1 a), Show (v2 a)) => v1 a -> v2 a -> String
showIfFirstEqual v1 v2 =
  if VG.head v1 == VG.last v2
    then show v1
    else show v2

showIfFirstEqualPrim :: (Eq a, Prim a, Show a) => VP.Vector a -> VP.Vector a -> String
showIfFirstEqualPrim v1 v2 =
  if VP.head v1 == VP.last v2
    then show v1
    else show v2
```

**Comment by lehins** [comment] 2020-02-02 21:52
Not only in the first example two vectors can be different, but you also end up with constraints that are already available for concrete vector types. `Show`,  `Eq`, `Ord`, ... list goes on

**Comment by lehins** [comment] 2020-02-02 21:54
From the user's perspective, especially a novice user, this is will result in a head explosion

**Comment by cartazio** [comment] 2020-02-02 22:01
i agree. What i'm proposing is, maybe the right long term fix is add to ghc a way to instantiate the type variable of a module when reexporting it. sortah like a sibling of DerivingVia or defaulting rules

It seems to me, perhaps one way we could do it ourselves, is via backpack? (though i'm not sure if this actually matches up with how backpack works, and that has its own pain points perhaps)

**Comment by cartazio** [comment] 2020-02-02 22:02
to restate: i absolutely agree with that user concern, and I merely wonder how we can use technology to fix that while making the end result simpler! :) 

either a) the technology exists or b) we need to add it to ghc :)

**Comment by lehins** [comment] 2020-02-02 22:02
@cartazio I will agree with @Shimuuar, that the only downside to keeping monomorphic versions is the documentation, which I believe there is a good solution for in #296 

If you want to try out the polymorphic alternative and see how it feels, try out using `massiv`. This is the approach I've taken there and trust me, if I could, I would provide monomorphic alternatives in massiv as well, but I just don't have enough bandwidth to do that.

Solving this problem at ghc level is not gonna help us, since we need to support many much older versions. Same thing with bagpack. Are we ready to drop old versions? Are we sure that all yools even support it?

**Comment by cartazio** [comment] 2020-02-02 22:05
that actually suggest a crazy evil idea that i think you'll hate, but might like:

maybe theres some dumb way we can abuse CPP or template haskell ?

**Comment by cartazio** [comment] 2020-02-02 22:07
i'm not suggesting that some of those (improve XYZ in ghc) approaches are ones we could enjoy today. but they do lay the ground work to allowing those ideas to work as the support window shifts over the coming years. "technology we will be happy about  having already in 3-5years" even if we dont benefit from it ourselves immediately.

**Comment by lehins** [comment] 2020-02-02 22:09
You are right! I would hate it! :D

> maybe theres some dumb way we can abuse CPP or template haskell

To all honesty, I don't think it is a big problem. Adding few lines of code for each **new** function is not as big of a deal.

Solving this problem in ghc for future generations would be a good approach, but that has nothing to do with vector today. Such ticket should live in ghc issue tracker, not here. Since, if solved it would only be helpful to vector in another decade or so. 3-5 yeasr is a significant underestimate

**Comment by cartazio** [comment] 2020-02-02 22:13
time will tell. I just want to emphasize that we should think about what we wish we could have the compiler for haskell do to support vector, and nerdsnipe ousrselves or ghc contributors into collabing on making those improvments happen.

I guess one important question is what is the current users of ghc 7.6-7.10? what linux/OS distros are still shipping them? or where the new user instllation funnel ends up there

**Comment by lehins** [comment] 2020-02-02 22:19
Sure. Whatever the decision/solution there will be for this problem, we must ensure it does not affect the user experience. As it is right now, `vector` is pretty easy to get started with for a novice user, we wanna keep it that way.

Just FYI, I do agree that current approach is just boilerplate, but as it is right now, it seems to me as necessary boiler plate.

**Comment by cartazio** [comment] 2020-02-02 22:20
yes, it sounds like we agree on where the stuff stands today. I just want use all to make sure we poke/challenge the future to be a great one for venerable  vector as well as its more agile friends and family

**Comment by Shimuuar** [comment] 2020-02-03 09:46
> maybe theres some dumb way we can abuse CPP or template haskell ?

TH doesn't work for crosscompiling so it's out. And CPP Is a monkey's paw. It can and will what you want. But you're tempting fate

> @Shimuuar lol. Don't exaggerate :D

I don't. Operative word is "without mistakes". One make change once or twice without problems, but copy-paste mistakes will start creeping in eventually. Why eventually. I skrewed up copy-pasting in #295 already. BTW #296 looks good but still suffers from repetition

@cartazio it looks like this problem could be solved with first class modules. Essentially we want same module but with monomorphised functions. But this is _huge_ undertaking and as @lehins already said will takes years to implement and more years before it could be used in vector (3? 6? releases)

IMHO only downsides to reexport are possibly broken code when vector type is inferred from function not from parameter. Something like: `U.sum $ U.enumFromTo 1 100`. It should be rare but that require digging through hackage to quantify. And as @lehins noticed inferred type signatures and type errors become much worse

**Comment by merijn** [comment] 2020-02-03 09:54
>  it looks like this problem could be solved with first class modules. Essentially we want same module but with monomorphised functions.

Actually, couldn't this be tackled by backpack? But then again, I don't know how stable backpack is at the moment.

**Comment by lehins** [comment] 2020-02-03 14:01
@Shimuuar That's why we have PR reviews and issue reporting. No matter what you do, be it copy/paste or write yourself, mistakes in haddock are inevitable. We are all in it together to reduce the chance of such mistakes from happening. And there are a lot of eyes on vector haddock, so even if something gets screwed up, it will be noticed pretty quick, and fixing haddock is easy, it doesn't even require a minor version bump. 

> Why eventually. I skrewed up copy-pasting in #295 already. BTW #296 looks good but still suffers from repetition

You messed up in #295 but I noticed it during the review and together we make sure that haddock (and code) is good.

Do not forget, that there is a lot of closed source projects that also use vector, so hackage alone quantifies only a small part of it
>  It should be rare but that require digging through hackage to quantify

@merijn backpack is only available with ghc-8.2, vector supports much older versions. Plus tooling around backpack isn't yet mature (I am not talking about cabal here)

**Comment by Shimuuar** [comment] 2020-02-03 22:12
Reviewers are just as fallible. But they do bring bug rates a lot. I guess our difference in priorities come from differences of experience. I worked a lot in situations when code review is not available/practical. And in that case your first line of defense is to avoid all situations where you're likely to make mistake. 

Mining hackage will give some biased estimate of a problem. At least if it is bad, it _is_ bad. But overall I think we can close this issue and concentrate on documentation (#296)

**Comment by cartazio** [comment] 2020-02-03 22:42
mining hackage to estimate what? @Shimuuar could you clarify which remarks / topics each thing is addressing? (i'm having some some trouble disambiguating which parts of the thread/which concerns you're speaking to)

**Comment by Shimuuar** [comment] 2020-02-04 09:20
To estimate amount of breakage which change (whatever change) will induce. It's only source of information available to us but it provides biased estimate: a lot of libraries and very few applications. While for closed source/unpublished code situation is probably inverse. 

P.S. I guess I'm not very clear when writing past midnight

**Comment by cartazio** [comment] 2020-02-04 12:38
It happens. :)

This is what made me realize I need to take a serious look at at backpack.
To understand if it can give us perfect compat AND nice things.

The point I think Merijn was driving towards was that most and libraries
applications have top level type signatures. Especially since missing top
level signatures is a default warning in ghc  .

 Which the simple just reexport  vector  generics approach would work with.
 (And would definitely work with haddock and stack ).

**Comment by Shimuuar** [comment] 2020-06-11 18:15
AFAIR we reached consensus that we shouldn't reexport and maintain status quo. 

I propose closing issue. @lehins @Bodigrim. You opinion?

**Comment by Bodigrim** [comment] 2020-06-11 18:36
I think that having monomorphic modules is invaluable. Error messages for mutable vectors are already scary enough (and mostly because of being polymorphic by `PrimMonad` - while 95% of applications work in `ST`) and it is often convenient to switch to `Data.Vector` to get a prototype right, without fighting against tons of "no instance" / "amibiguous instances" stuff. 

I also often take an advantage of monomorphic types, when write `U.sum . U.generate f`. 

AFAIU @lehins has already stated his opinion clear enough, so since we are all in agreement, closing.

**Closed by Bodigrim** 2020-06-11 18:36 UTC
