### ISSUE TITLE
Segfault when using enumFromTo with maxBound as upper bound

### ISSUE THREAD

**Issue by noughtmare** [haskell/vector#188] opened 2017-11-30 16:58 UTC
I get a segfault when running the following code:

```Haskell
import qualified Data.Vector as V
import Data.Word

main :: IO ()
main = (V.enumFromTo (pred maxBound) maxBound :: V.Vector Word8) `seq` return ()
```

```
$ cabal --version
cabal-install version 2.0.0.0
compiled using version 2.0.0.2 of the Cabal library 
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.2.1
```

I now use `enumFromN` as a workaround, that works.

This happens with `vector-0.12.0.1` from hackage.

**Comment by glguy** [comment] 2017-11-30 17:09
This only happens with optimizations enabled for me. Looking at the core it seems like what's happening is the counter from 0 to 255 is being incremented by one and then being compared with `<=` to 255. I think that the counter is overflowing back to 0 and so the code writes past the end of the allocated vector (which I checked is correctly allocated to 256 elements)

**Comment by glguy** [comment] 2017-11-30 17:13
I updated the ticket title because this isn't specific to thaw, or to Word8, it is reproducible with Word16, Word32, etc as long as the upper bound is set to `maxBound`

**Comment by noughtmare** [comment] 2017-11-30 17:25
I have also updated the code.

**Comment by dolio** [comment] 2017-12-10 21:38
Do we know what's broken? Tracing along the `enumFromTo` implementation, I get to a corresponding function on (monadic) bundles. But that just calls `fromList [x .. y]`.

Is it `unstream` that's broken?

**Comment by glguy** [comment] 2018-08-24 20:20
The bug is in this code: https://github.com/haskell/vector/blob/master/Data/Vector/Fusion/Bundle/Monadic.hs#L758-L767

Specifically the `+1` on this line is overflowing.

https://github.com/haskell/vector/blob/master/Data/Vector/Fusion/Bundle/Monadic.hs#L766

**Comment by cartazio** [comment] 2019-07-12 22:13
booo, this needs to be fixed, adding to action list :)

**Comment by cartazio** [comment] 2020-01-21 02:36
brr, this has been languishing for too long

**Comment by cartazio** [comment] 2020-01-31 02:49
this should be resolved in master now

**Closed by cartazio** 2020-01-31 02:49 UTC
Labels: bug, prioritized
