### ISSUE TITLE
Add pattern matching for head and tail

### ISSUE THREAD

**Issue by flip111** [haskell/vector#344] opened 2020-12-29 00:52 UTC
Could something like this be added ?

```haskell
unConsV :: V.Vector a -> Maybe (a,V.Vector a)
unConsV v
  | V.null v = Nothing
  | otherwise = Just (V.head v,V.tail v)
  {-# COMPLETE NilV,ConsV #-}
  pattern NilV :: V.Vector a
  pattern NilV <- (unConsV -> Nothing)
  pattern ConsV :: a -> V.Vector a -> V.Vector a
  pattern ConsV x xs <- (unConsV -> Just (x,xs))
```

or

```haskell
unConsV :: V.Vector a -> Maybe (a,V.Vector a)
unConsV v
  | V.null v = Nothing
  | otherwise = Just (V.head v,V.tail v)
  {-# COMPLETE NilV,(:@) #-}
  pattern NilV :: V.Vector a
  pattern NilV <- (unConsV -> Nothing)
    where {NilV = V.empty}
  infixr 5 :@
  pattern (:@) :: a -> V.Vector a -> V.Vector a
  pattern x :@ xs <- (unConsV -> Just (x,xs))
    where {(:@) = V.cons}
```

**Comment by Bodigrim** [comment] 2020-12-29 18:36
`uncons` has been added in #212.

Not convinced that there is much added value in pattern synonyms here. I do not see much difference between

```haskell
case uncons v of 
  Nothing -> ... 
  Just (_, _) -> ...
```

and 

```haskell
case v of 
  NilV -> ... 
  ConsV _ _ -> ...
```

**Comment by dolio** [comment] 2021-01-01 01:28
That example is pretty much the best case scenario for making the patterns look useless, though. The difference could also be more like:

```haskell
f NilV = ...
f (ConsV x xs) = ...
```
versus
```haskell
f (uncons -> Nothing) = ...
f (uncons -> Just (x, xs)) = ...
```
And there could be additional matches/guards that make converting to a case statement non-trivial.

**Comment by Bodigrim** [comment] 2021-01-01 13:03
I still would not call the difference crucial, to be honest. 

* Bidirectional pattern synonyms (as in the second example of https://github.com/haskell/vector/issues/344#issue-775644441) encourage people to use vectors as lists. This is an anti-pattern, and I do not want to promote it. 
* Unidirectional pattern synonyms (as in the first example ibidem) are a lie: one has constantly bear in mind that while they look indistinguishable from constructors, they are not. From my perspective, a minor syntactic flexibility is not worth it. 

That said, I do not feel very strongly about these points. Let's see what other maintainers think.

**Comment by lehins** [comment] 2021-01-01 17:40
I totally agree with all that @Bodigrim said. I am closing this ticket as duplicate of #212 and I am against `Cons` and `Nil` pattern synonyms. Cons and snoc have potential of O(n) complexity when computation can't be fused, so it needs to be an explicit function call.

**Closed by lehins** 2021-01-01 17:40 UTC
