### ISSUE TITLE
Build broken with latest primitive

### ISSUE THREAD

**Issue by osa1** [haskell/vector#256] opened 2019-09-24 08:23 UTC
vector currently cannot be built with the latest primitive (from the git repo), which makes things harder when testing GHC HEAD. I have a patch (see below), but it probably doesn't have the necessary CPPs to make the package build with older primitive+GHCs _and_ newer primitive+GHC head so I'm not submitting a PR for now.

Note that some fromEnumTo tests fail with the patch below, but in my testing they also fail with GHC 8.6.5, so that's probably not a problem with the patch.

---

```diff
diff --git a/Data/Vector/Storable/Mutable.hs b/Data/Vector/Storable/Mutable.hs
index 860c6dc..7f55a2e 100644
--- a/Data/Vector/Storable/Mutable.hs
+++ b/Data/Vector/Storable/Mutable.hs
@@ -68,7 +68,7 @@ import Control.DeepSeq ( NFData(rnf)
                        )
 
 import qualified Data.Vector.Generic.Mutable as G
-import Data.Vector.Storable.Internal
+import Data.Vector.Storable.Internal hiding (setPtr)
 
 import Foreign.Storable
 import Foreign.ForeignPtr
@@ -83,14 +83,14 @@ import GHC.ForeignPtr
 #endif
 
 import Foreign.Ptr ()
-import Foreign.Marshal.Array ( advancePtr, copyArray, moveArray )
+import Foreign.Marshal.Array ( copyArray, moveArray )
 
 import Control.Monad.Primitive
-import Data.Primitive.Addr
+import Data.Primitive.Ptr
 import Data.Primitive.Types (Prim)
 
 import GHC.Word (Word8, Word16, Word32, Word64)
-import GHC.Ptr (Ptr(..))
+import GHC.Ptr (plusPtr)
 
 import Prelude hiding ( length, null, replicate, reverse, map, read,
                         take, drop, splitAt, init, tail )
@@ -126,12 +126,12 @@ instance Storable a => G.MVector MVector a where
   basicLength (MVector n _) = n
 
   {-# INLINE basicUnsafeSlice #-}
-  basicUnsafeSlice j m (MVector _ fp) = MVector m (updPtr (`advancePtr` j) fp)
+  basicUnsafeSlice j m (MVector _ fp) = MVector m (updPtr (`plusPtr` (j * sizeOf (undefined :: a))) fp)
 
   -- FIXME: this relies on non-portable pointer comparisons
   {-# INLINE basicOverlaps #-}
   basicOverlaps (MVector m fp) (MVector n fq)
-    = between p q (q `advancePtr` n) || between q p (p `advancePtr` m)
+    = between p q (q `plusPtr` (n * sizeOf (undefined :: a))) || between q p (p `plusPtr` (m * sizeOf (undefined :: a)))
     where
       between x y z = x >= y && x < z
       p = getPtr fp
@@ -181,8 +181,7 @@ instance Storable a => G.MVector MVector a where
 storableZero :: forall a m. (Storable a, PrimMonad m) => MVector (PrimState m) a -> m ()
 {-# INLINE storableZero #-}
 storableZero (MVector n fp) = unsafePrimToPrim . withForeignPtr fp $ \(Ptr p) -> do
-  let q = Addr p
-  setAddr q byteSize (0 :: Word8)
+  setPtr (Ptr p) byteSize (0 :: Word8)
  where
  x :: a
  x = undefined
@@ -190,7 +189,7 @@ storableZero (MVector n fp) = unsafePrimToPrim . withForeignPtr fp $ \(Ptr p) ->
  byteSize :: Int
  byteSize = n * sizeOf x
 
-storableSet :: (Storable a, PrimMonad m) => MVector (PrimState m) a -> a -> m ()
+storableSet :: forall a m . (Storable a, PrimMonad m) => MVector (PrimState m) a -> a -> m ()
 {-# INLINE storableSet #-}
 storableSet (MVector n fp) x
   | n == 0 = return ()
@@ -205,9 +204,9 @@ storableSet (MVector n fp) x
 
                        let do_set i
                              | 2*i < n = do
-                                 copyArray (p `advancePtr` i) p i
+                                 copyArray (p `plusPtr` (i * sizeOf (undefined :: a))) p i
                                  do_set (2*i)
-                             | otherwise = copyArray (p `advancePtr` i) p (n-i)
+                             | otherwise = copyArray (p `plusPtr` (i * sizeOf (undefined :: a))) p (n-i)
 
                        do_set 1
 
@@ -216,9 +215,8 @@ storableSetAsPrim
 {-# INLINE [0] storableSetAsPrim #-}
 storableSetAsPrim n fp x y = withForeignPtr fp $ \(Ptr p) -> do
   poke (Ptr p) x
-  let q = Addr p
-  w <- readOffAddr q 0
-  setAddr (q `plusAddr` sizeOf x) (n-1) (w `asTypeOf` y)
+  w <- readOffPtr (Ptr p) 0
+  setPtr (Ptr p `plusPtr` sizeOf x) (n-1) (w `asTypeOf` y)
 
 {-# INLINE mallocVector #-}
 mallocVector :: Storable a => Int -> IO (ForeignPtr a)
@@ -512,7 +510,7 @@ unsafeCast (MVector n fp)
 -- could have been frozen before the modification.
 --
 --  If your offset is 0 it is more efficient to use 'unsafeFromForeignPtr0'.
-unsafeFromForeignPtr :: Storable a
+unsafeFromForeignPtr :: forall a s . Storable a
                      => ForeignPtr a    -- ^ pointer
                      -> Int             -- ^ offset
                      -> Int             -- ^ length
@@ -520,7 +518,7 @@ unsafeFromForeignPtr :: Storable a
 {-# INLINE_FUSED unsafeFromForeignPtr #-}
 unsafeFromForeignPtr fp i n = unsafeFromForeignPtr0 fp' n
     where
-      fp' = updPtr (`advancePtr` i) fp
+      fp' = updPtr (`plusPtr` (i * sizeOf (undefined :: a))) fp
 
 {-# RULES
 "unsafeFromForeignPtr fp 0 n -> unsafeFromForeignPtr0 fp n " forall fp n.
```

**Comment by RyanGlScott** [comment] 2019-09-24 12:06
I am unable to reproduce the build failure you're alluding to. I'm using:

* `primitive` commit haskell/primitive@c446914899b1ce5c32614df2833b807971bb5c62
* `vector-0.12.0.3`

I've tried this combination with GHC 8.6.5, 8.8.1, and HEAD (commit [1b7e1d31](https://gitlab.haskell.org/ghc/ghc/commit/1b7e1d31fee4176608e46d45ddc195e313eed978)), and they all build without issue.

**Comment by RyanGlScott** [comment] 2019-09-24 12:45
Ah, you're building from `vector` HEAD, not from Hackage then. Do note that the [`master` branch does not yet](https://github.com/haskell/vector/issues/255) have [this commit](https://github.com/haskell/vector/commit/eedcf5e4b74e0dd3b6350bbd67dde2be231d47c4#diff-2974bcc0b585c93d24b5b93684e02310) (removing the `Data.Primitive.Addr` import) from the `v0.12` branch, which is what `vector-0.12.0.3` from Hackage is currently synced against.

**Comment by osa1** [comment] 2019-09-24 12:48
Is the `v0.12` branch where the development is happening these days? If so maybe it should be the default branch on Github so that people won't get confused like me and waste time try to fix it.

**Comment by cartazio** [comment] 2019-09-25 02:28
yeah, i need to reconcile against https://github.com/haskell/vector/tree/v0.12 branch

**Comment by cartazio** [comment] 2019-09-25 02:30
i'll leave this ticket open for now, but its really just me needing to move the fixups over from 0.12

**Comment by asr** [comment] 2019-11-28 03:00
I had the same problem in the OP because I also used the `master` branch.

**Comment by lehins** [comment] 2019-11-28 12:52
@asr see my comment here: https://github.com/haskell/vector/issues/258#issuecomment-536775528
You are definitely not the first one to assume that master is the base branch and should have all the bug fixes in it.

**Comment by cartazio** [comment] 2019-11-28 14:11
I need to forward port these.  Agreed.

**Comment by sjakobi** [comment] 2019-12-13 17:29
The broken testsuite is very confusing. Maybe the failing testcases can be marked as expected failures until they are fixed?!

**Comment by cartazio** [comment] 2019-12-13 20:15
I’m using this weekend and the next two weeks to catch-up on vector stuff.
Thanks for pinging

**Comment by cartazio** [comment] 2020-01-10 22:19
@osa1  et al, master should build everwhere now

**Comment by cartazio** [comment] 2020-01-10 22:20
closing, comment if i'mm wrong :)

**Closed by cartazio** 2020-01-10 22:20 UTC
