### ISSUE TITLE
last doesn't always fuse?

### ISSUE THREAD

**Issue by yongqli** [haskell/vector#73] opened 2015-01-26 00:55 UTC
It seems that `last` doesn't completely fuse away?

    import Linear
    benchLast :: Int -> M44 Double
    benchLast n =
      G.last $ VU.replicate n (pure 0)

    benchLast2 :: Int -> M44 Double
    benchLast2 n =
      (G.! (n-1)) $ VU.replicate n (pure 0)

With `n = 2000000`, I see
    benchmarking benchmarks/last
    time                 3.345 ms   (3.321 ms .. 3.369 ms)
    benchmarking benchmarks/last2
    time                 482.2 μs   (475.0 μs .. 494.2 μs)

I had to use `M44` from `Linear` to make the difference more noticeable.

**Comment by cartazio** [comment] 2016-07-24 19:48
i think the first definition of last is slow PRECISELY because its fusing, so repeated invocations you may have repeated computation of looping through the stream, whereas in the latter its sharing and then just indexing. i could be wrong, but marking this as wontfix/closed for now.

if you believe theres a performance issue in vector that should be deemed a bug, please provide a more reproduciable benchmark :)

**Closed by cartazio** 2016-07-24 19:48 UTC
