### ISSUE TITLE
Unboxing Maybe and Either

### ISSUE THREAD

**Issue by andrewthad** [haskell/vector#119] opened 2016-06-24 20:44 UTC
The following two instances (plus the other instances that they imply) should be writable:

    instance Unbox a => Unbox (Maybe a)
    instance (Unbox a, Unbox b) => Unbox (Either a b)

In the [examples for vector-th-unbox](http://hackage.haskell.org/package/vector-th-unbox-0.2.1.4/docs/Data-Vector-Unboxed-Deriving.html), the way to do the `Maybe` instance is shown (however, it has a `Default a` constraint that could be avoided). I would be happy to add these to `vector` sometime if others agree that this is a good idea.

**Comment by dolio** [comment] 2016-06-26 02:08
I'm unsure. But I could be convinced.

I think a good implementation more complicated than that page suggests. For mutable vectors, the best you can do (I think), is have underlying vectors which contain slots for all possibilities. So an n-length `Maybe a` vector requires an n-length `a` vector, and some elements might be garbage.

But immutable vectors can actually be represented in a nicer way. You can have an underlying `a` vector containing only the `Just` elements, and store information about which `Maybe a` index maps to which `a`, and which to `Nothing`. Similarly, you can store `a` and `b` values and information about which `Either a b` index maps to which vector and which index in that vector.

However, implementing these encodings can be tricky, depending on what operations you want to support well (might not be that bad for vector); and it also means that freeze and thaw (for instance) must do copies, because the representations are completely different.

So, it'd be good to have some more discussion before saying yes.

**Comment by andrewthad** [comment] 2016-06-26 22:31
The representation I was thinking of was a little different. Mutable and immutable vectors would have the same representation. For `Maybe a`, it would be stored as two vectors. The first would basically be a vector of `Bool`s. The second would be a vector of `a`s. If the first vector has `True` at an index, then it means that the second vectors `a` value at that same index is wrapped up in a `Just`. If not, that value must be ignored. The representation for `Either a b` would follow a similar scheme, except that there would be three vectors instead of just two.

Whatever representation is used, I think that the mutable and immutable variants should have the same representation. If `unsafeFreeze` and `unsafeThaw` aren't O(1) operations, that would be somewhat confusing.

**Comment by cartazio** [comment] 2016-06-26 22:43
I've discussed this sort of representation with Edwardk before, and he
raised the very valid objection that you need to be able to guarantee
something along the lines that zerod memory is valid for any choice in type
if you want the instances to behave nice.

**Comment by andrewthad** [comment] 2016-06-27 12:05
@cartazio Fortunately, for all the types that have an `Unbox` instance, zeroed memory is valid. But, I can't see why that would be necessary. If `Maybe a` were represented as a pair of vectors, if someone wrote `Nothing` to an index, the internal behavior would be to only write to the first vector in the pair (setting it to `False`) and leave the second vector untouched.

**Comment by cartazio** [comment] 2016-06-27 12:56
I think @edwardk can explain this better perhaps

**Comment by cartazio** [comment] 2016-06-27 12:57
I mean @kmett

**Comment by cartazio** [comment] 2016-06-27 12:57
@ekmett

**Comment by ndmitchell** [comment] 2016-06-27 13:40
Wouldn't `Vector (Bool, a)` be a better representation for a vector of `Maybe a`? You get only one vector, so freeze/unfreeze is simpler.

**Comment by andrewthad** [comment] 2016-06-27 13:51
@ndmitchell For tuples unboxed vectors are represented as a structure of arrays, not an array of structures. So, `Unbox.Vector (Bool, a)` is already represented as two vectors under the hood. So, ultimately, `Unbox.Vector (Bool, a)` and `(Unbox.Vector Bool, Unbox.Vector a)` have identical representations. I prefer the latter so that we could avoid going through a tuple as an intermediate representation.

**Comment by ndmitchell** [comment] 2016-06-27 14:30
@andrewthad - ah, I hadn't realised that.

**Comment by cartazio** [comment] 2016-07-24 18:56
ok, so my current thoughts on this is that Vector is for *Dense* memory buffers, and the type classes currently require every single Vector typeclass instance to have a corresponding MVector instance.



A sparse friendly struct of arrays format has a very different representational contract in terms of data structures than a dense format, and the vector package isn't equipped for that.

@andrewthad  could you prototype this in userland first? Also the zeroing assumption is a STRONG one to make, and i'm not quite certain its true in a useful way ... :( 

closing for now because even though we zero out fresh buffers for now, we dont actually specify / require that zero'd data need be valid for the end user's data type

**Closed by cartazio** 2016-07-24 18:56 UTC

**Comment by twhitehead** [comment] 2018-04-10 18:36
Implemented this a couple of days ago using the `Vector (Bool,a)` approach for some other code and then came across this bug report today, so pulled it out and uploaded it to github

https://github.com/twhitehead/vector-maybe

To get a hold of a default value, I just created an uninitialized length 1 vector of the underlying type and read the first element.  Seems this should do a one-time cast from a 0 initialized memory region.

**Comment by cartazio** [comment] 2018-04-10 18:48
Hrm... can we provide a safe instance of this sort of type for anythign
aside from perhaps Floating, Integral, and or perhaps Bits instances?

**Comment by andrewthad** [comment] 2018-04-10 19:01
Using an uninitialized vector to get the default element is no better than just using 0 as the default element. Also, I still don't really understand why it's important for the bits that comprise the default element to be a valid representation of a value. You can just leave the data constructor unexported, and then no one can get access to the unboxed vector that contains potentially invalid elements.

**Comment by twhitehead** [comment] 2018-04-10 19:10
@cartazio that's a fair point.  It wasn't clear to me though if the existing unboxed vector code already depended on being able to cast from 0 uninitialized memory or not though.

@andrewthad I think the issue is whether casting from zero initialized memory always gives a valid encoding for all the unboxed types.  I have heard of cases cases, for instance, where things have blown up because internally the compiler winds up trying to pass essentially uninitialized memory through a float point register and it blows up loading it because the uninitialized memory happens to have an arrangement of bits that isn't a valid float encoding.

From reading the current GHC documentation on [unboxed sums](http://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#unboxed-sums), I actually expect this sort of thing might actually be possibly to happen as it seems to be designed to carefully keep word and floating values separate in memory.

**Comment by twhitehead** [comment] 2018-04-10 19:14
Perhaps the most sensible thing to do is as @cartazio suggested earlier and simply not define it in terms of the tuple.  Shouldn't be too difficult to do.  Pretty much just lift the [existing 2-tuple code](https://github.com/haskell/vector/blob/master/internal/unbox-tuple-instances#L2) and tweak the read and write functions to not read/write both components if the value is masked.

**Comment by andrewthad** [comment] 2018-04-10 19:15
@twhitehead At runtime, the uninitialized memory should *never* actually get loaded into a register. As long as it's just sitting in memory, it's completely safe. If you actually index into it, then maybe you could make some bad stuff happen, but this shouldn't ever happen.

**Comment by twhitehead** [comment] 2018-04-10 21:30
It wasn't too difficult so I rewrote [my code](https://github.com/twhitehead/vector-maybe) as something independent (pretty much a straight ripoff of the unboxed 2-tuple) and not just a wrapper around `(Bool,a)`.  Haven't done a whole lot of testing other than creating and played with some unboxed `Maybe Int` vectors in GHCi, but it seems things are working fine.

As mentioned in the code, I expect it would be better if the unboxed `Bool` was a bit vector (a lot more cache friendly) as in the [unboxed array Bool implementation](https://hackage.haskell.org/package/array-0.5.2.0/docs/Data-Array-Unboxed.html).  Could use the the [unboxed bit vector implementation](https://hackage.haskell.org/package/bit-vector-0.2.0/docs/Data-Vector-Bit.html), but it seems really like unboxed `Bool` should maybe be optimized instead.

**Comment by andrewthad** [comment] 2018-04-10 21:33
Thanks for explaining that more. I agree with you that using Tuple  directly would be bad. We definitely don’t ever want to perform a load on a  we definitely don’t ever want to perform a load on a piece of memory that was not explicitly set to a known good value.
